### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/rest-framework#294]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] base_rest - By @StefanRijnhart - #313
- [ ] base_rest_auth_api_key - By @StefanRijnhart - #313
- [ ] base_rest_auth_jwt
- [ ] base_rest_auth_user_service
- [ ] base_rest_datamodel - By @StefanRijnhart - #313
- [ ] base_rest_demo - By @StefanRijnhart - #313
- [ ] base_rest_pydantic - By @StefanRijnhart - #313
- [ ] datamodel - By @StefanRijnhart - #313
- [ ] extendable - By @StefanRijnhart - #313
- [ ] graphql_base - By @rconjour - #323
- [ ] graphql_demo - By @dduarte-odoogap - #398
- [ ] model_serializer
- [ ] pydantic - By @StefanRijnhart - #313
- [ ] rest_log - By @heliaktiv - #318

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by flachica** [comment]
Working in a new module "fastapi_log" like "rest_log" but bases in "fatsapi" instead of "base_rest"
